### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by weihao** [hmanzur/actions-aws-eb#1]
```
Run hmanzur/actions-aws-eb@v1
e87b52:76200f41b2d54a50a893b843707ac5e6  "deploy ***"
usage: eb (sub-commands ...) [options ...] {arguments ...}
eb: error: unrecognized arguments: deploy ***
```

```
      - name: Deploy
        uses: hmanzur/actions-aws-eb@v1
        with:
          command: 'deploy ${{ secrets.ENVIRONMENT_NAME }}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-east-1"
```
