### ISSUE TITLE
ERROR: TypeError - can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by tawanda** [hmanzur/actions-aws-eb#7]
Hi, I started getting that error when I updated to a new environment

this is my config

```
- name: Beanstalk Deploy
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'deploy --staged'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.EB_USER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.EB_USER_SECRET_ACCESS_KEY }}
          APPLICATION_NAME: my-api
          ENVIRONMENT_NAME: my-staging-api
          AWS_DEFAULT_REGION: ap-northeast-2
```

Github Actions was down today so not sure if they changed something and now this version is no longer compatible?
