### ISSUE TITLE
Error: You must first run "eb init".

### ISSUE THREAD

**Issue by jadbox** [hmanzur/actions-aws-eb#8]
I get this error when I try to deploy, and I do have my `.elasticbeanstalk/config.yml` committed into the repo.

**Comment by ilmoi** [comment]
I'm sure you checked this, but just in case make sure that your `.gitignore` is not preventting `.elasticbeanstalk/config.yml` from being uploaded. EB automatically adds stuff to your gitignore which prevents upload. That was the problem for me.

**Comment by pllearns** [comment]
Interesting that we would need to .gitignore the config, or worry about the config when this should include `eb init`. We are already bringing in the secrets into the action. Just curious as to why we couldn't include the eb init script in the action, maybe in commands with `deploy`?

**Comment by tamsanh** [comment]
Also make sure that you use `actions/checkout@v2`, so that the actual `.elasticbeanstalk/config.yml` file can be read from the commit.

Ex:

```
jobs:
  update_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'setenv BUNDLE_URL=${{ secrets.BUNDLE_URL }}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
```
